# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        node-version: [4.x, 6.x, 8.x, 10.x, 12.x, 14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        include:
          - node-version: 4.x
            npm-i: "eslint@4.x eslint-plugin-mocha@4.x mocha@5.x nyc@11.x"

          - node-version: 6.x
            npm-i: "eslint@5.x eslint-plugin-mocha@5.x mocha@6.x nyc@14.x"

          - node-version: 8.x
            npm-i: "eslint@6.x eslint-plugin-mocha@6.x mocha@7.x"

          - node-version: 10.x
            npm-i: "eslint@7.x eslint-plugin-mocha@8.x mocha@8.x"

          - node-version: 12.x
            npm-i: "eslint-plugin-mocha@9.x mocha@9.x"

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Configure npm
      run: npm config set loglevel error

    - name: Get npm version
      id: npm-version
      run: |
        npm -v
        npmMajorVer=$(npm -v | cut -d. -f1)
        echo "major=$npmMajorVer" >> $GITHUB_OUTPUT

    - name: Install downgraded modules ${{ matrix.npm-i }}
      run: |
        npm install --save-dev ${{ matrix.npm-i }}
        if [ ${{ steps.npm-version.outputs.major }} -le 5 ]; then
          npm install
        fi
      if: matrix.npm-i != ''

    - run: npm install
      if: matrix.npm-i == '' && steps.npm-version.outputs.major <= 5

    - run: npm ci
      if: matrix.npm-i == '' && steps.npm-version.outputs.major > 5

    - name: List dependencies
      run: npm ls --depth=0 --dev | npm ls --depth=0 --prod
      continue-on-error: true

    - name: Compatibility fix for wrap-wrap@1.2.4 - 1.2.5 for Node.js 4 (eslint@>=2 <=7.0.0-alpha.3 > optionator@^0.8 > word-wrap@~1.2.3)
      run: |
        cat ./node_modules/eslint/node_modules/optionator/node_modules/word-wrap/index.js
        sed -i 's/let/var/g' ./node_modules/eslint/node_modules/optionator/node_modules/word-wrap/index.js
        cat ./node_modules/eslint/node_modules/optionator/node_modules/word-wrap/index.js
      if: matrix.node-version == '4.x'

    - run: npm run build --if-present
    - run: npm test
